name: confectionery_storie
description: My Confectionery Storie
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.2+3
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_modular: ^6.3.4
  google_fonts: ^6.2.1
  font_awesome_flutter:
  flutter_secure_storage: ^9.2.2
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  path_provider: ^2.1.5

dev_dependencies:
  build_runner: ^2.4.14
  hive_generator: ^2.0.1

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true