# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

source 'https://github.com/cleveradssolutions/CAS-Specs.git'
source 'https://github.com/CocoaPods/Specs.git'
$casVersion = '3.9.8'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  pod 'CleverAdsSolutions-SDK/Optimal', $casVersion
  pod 'CleverAdsSolutions-SDK/Kidoz', $casVersion
  pod 'CleverAdsSolutions-SDK/StartIO', $casVersion
  pod 'CleverAdsSolutions-SDK/CrossPromo', $casVersion
  pod 'CleverAdsSolutions-SDK/HyprMX', $casVersion
  pod 'CleverAdsSolutions-SDK/Smaato', $casVersion
  pod 'CleverAdsSolutions-SDK/Ogury', $casVersion
  pod 'CleverAdsSolutions-SDK/Madex', $casVersion
  pod 'CleverAdsSolutions-SDK/LoopMe', $casVersion

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
    bitcode_strip_path = `xcrun --find bitcode_strip`.chop!
    def strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
        framework_path = File.join(Dir.pwd, framework_relative_path)
        command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
        puts "Stripping bitcode: #{command}"
        system(command)
    end

    framework_paths = [
        "Pods/smaato-ios-sdk/vendor/OMSDK_Smaato.xcframework/ios-arm64_armv7/OMSDK_Smaato.framework/OMSDK_Smaato",
        "Pods/LoopMeUnitedSDK/framework/LoopMeUnitedSDK/Core/Viewability/OMSDK/OMSDKswift/OMSDK_Loopme.xcframework/ios-arm64/OMSDK_Loopme.framework/OMSDK_Loopme",
        "Pods/KidozSDK/KidozSDK/KidozSDK.xcframework/ios-arm64/KidozSDK.framework/KidozSDK",
        "Pods/HyprMX/HyprMX.xcframework/ios-arm64/HyprMX.framework/HyprMX",
        "Pods/OguryAds/OMSDK_Ogury.xcframework/ios-arm64/OMSDK_Ogury.framework/OMSDK_Ogury",
        "Pods/MadexSDK/MadexSDK.xcframework/ios-arm64/MadexSDK.framework/MadexSDK",
    ]

    framework_paths.each do |framework_relative_path|
        strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
    end

  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
